# Jvascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version:

references:
  workspace_root: &workspace_root
    /tmp/workspace

  working_directory: &working_directory
    working_directory:
      *workspace_root

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  persist_to_workspace: &persist_to_workspace
    persist_to_workspace:
      root: *workspace_root
      paths:
        - .
jobs:
  build:
    working_directory: ~/sam
    docker:
      # specify the version you desire here
      - image: circleci/node:4
  test:
    <<: *working_directory
    steps:
      - checkout
      - run: curl https://raw.githubusercontent.com/apex/apex/master/install.sh | sh
      - run: apex version
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    # working_directory: ~/

    # steps:
    #   - checkout

      # Download and cache dependencies
      #- restore_cache:
      #    keys:
      #    - v1-dependencies-{{ checksum "event.json" }}
          # fallback to using the latest cache if no exact match is found
      #    - v1-dependencies-

      # - run: apt-get install -y curl
      # - run: curl https://raw.githubusercontent.com/apex/apex/master/install.sh | sh
      # - run: apex version

      # - save_cache:
      #    paths:
      #      - node_modules
      #    key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      # - run: sam local invoke -e event.json HelloWorld
