# Jvascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    # working_directory: ~/sam
    docker:
      # specify the version you desire here
      - image: circleci/python:3.6.1
  # test:
  #   <<: *working_directory
    steps:
      - checkout
      - run:
          command: |
            pwd
            sudo pip install awscli
            sudo apt-get install -y curl
            curl https://raw.githubusercontent.com/apex/apex/master/install.sh | sudo sh
        # apex version
        # aws configure set aws_access_key_id $DEV_AWS_ACCESS_KEY_ID
        # aws configure set aws_secret_access_key $DEV_AWS_SECRET_ACCESS_KEY
        # apex deploy --region ap-northeast-1 --env dev

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    # working_directory: ~/

    # steps:
    #   - checkout

      # Download and cache dependencies
      #- restore_cache:
      #    keys:
      #    - v1-dependencies-{{ checksum "event.json" }}
          # fallback to using the latest cache if no exact match is found
      #    - v1-dependencies-

      # - run: apt-get install -y curl
      # - run: curl https://raw.githubusercontent.com/apex/apex/master/install.sh | sh
      # - run: apex version

      # - save_cache:
      #    paths:
      #      - node_modules
      #    key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      # - run: sam local invoke -e event.json HelloWorld
